### ISSUE TITLE
[SlackAdapter Class] Missing if statement

### ISSUE THREAD

**Issue by GasparAcevedoZainSouthworks** [southworkscom/botkit#21]
### Description
Missing `if` in the _**SlackAdapter**_ constructor, when comparing with the _TS_ version.

### More Details
When comparing both the _C#_ & _TS_ _SlackAdapter_ versions, we noticed that in the base version we have this `if` ([link](https://github.com/southworkscom/botkit/blob/add/csharp-porting/packages/botbuilder-adapter-slack/src/slack_adapter.ts#L136)) which is not implemented in the C# version ([link](https://github.com/southworkscom/botkit/blob/add/csharp-porting/C%23/Botkit/Microsoft.BotKit.Adapters.Slack/SlackAdapter.cs#L55)). Also, this constructor can be refactored as follows, just for improving the readability:

```
if (this.options.BotToken != null)
{
  /// ... code
}
else
{
    if (string.IsNullOrEmpty(options.getTokenForTeam) || 
    string.IsNullOrEmpty(options.getBotUserByTeam))
    {
       throw new Exception(....);
    }

    if (string.IsNullOrEmpty(options.ClientId) || string.IsNullOrEmpty(options.ClientSecret) || 
    string.IsNullOrEmpty(options.RedirectUri) || options.Scopes.Length > 0)
    {
        throw new Exception(....);
    }
}

/// Continue w/the rest of the constructor
```

**Comment by matiasroldan6** [comment]
The original code in NodeJs `else if (!this.options.getTokenForTeam || !this.options.getBotUserByTeam)` checks for the existence of those methods (`getTokenForTeam` and `getBotUserByTeam`) because [they're both nullable](https://github.com/southworkscom/botkit/blob/add/csharp-porting/packages/botbuilder-adapter-slack/src/slack_adapter.ts#L670) in the class. In C# this is not necessary since the ISlackAdapterOptions interface will always require them.
The refactoring for legibility is viable, though.
